// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtoerzaawzyvjsfewjxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0b2VyemFhd3p5dmpzZmV3anhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODE3OTksImV4cCI6MjA2MDA1Nzc5OX0.VheQibE81i0qXi3UolfZENuTBmSrhicyZq70eEcPUwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);